[[pages]]
path = 'src/pages/card_distribution.py'
name = 'Card Distribution'
icon = ':bar_chart:'

[[pages]]
path = 'src/pages/detailed_distribution.py'
name = 'Detailed Distribution'
icon = ':bar_chart:'


[[pages]]
path = 'src/pages/burned_distribution.py'
name = 'Burned BCX'
icon = ':bar_chart:'
